
additionally_drop = ['anglez_rolling_mean_1',
                    'anglez_rolling_max_1',
                    'anglez_rolling_std_1',
                    'anglez_diff_1',
                    'anglez_diff_rolling_mean_1',
                    'anglez_diff_rolling_max_1',
                    'anglez_diff_rolling_std_1',
                    'enmo_rolling_max_1',
                    'enmo_rolling_std_1',
                    'enmo_diff_1',
                    'enmo_diff_rolling_mean_1',
                    'enmo_diff_rolling_max_1',
                    'enmo_diff_rolling_std_1']

bad_performer_drop = ["enmo_rolling_mean_1",
                    "enmo_rolling_max_5",
                    "anglez_diff_480",
                    "enmo_diff_rolling_mean_30",
                    "anglez_diff_rolling_mean_30",
                    "enmo_diff_480",
                    "enmo_diff_rolling_std_5",
                    "anglez_diff_rolling_max_5",
                    "anglez_diff_120",
                    "enmo_rolling_std_5",
                    "enmo_diff_120",
                    "anglez_diff_30",
                    "minute",
                    "enmo_diff_rolling_max_5",
                    "enmo_diff_30",
                    "anglez_diff_rolling_mean_5",
                    "enmo_diff_rolling_mean_5",
                    "anglez_diff_5",
                    "enmo_diff_5"]

columns_to_drop = ['series_id',
                'awake',
                'wearable_on',
                'seconds',
                'year',
                'anglez_abs',
                'enmo_abs'] + additionally_drop + bad_performer_drop 